name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or the branch you want to trigger the deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build  # Assuming this generates the dist/public directory

      - name: Remove /docs directory
        run: rm -rf docs  # Remove the existing docs directory

      - name: Copy build files to /docs
        run: cp -r dist/public/* docs/  # Copy files from dist/public to docs

      - name: Configure git
        run: |
          git config user.name "Your Name"
          git config user.email "youremail@example.com"

      - name: Commit and push changes
        run: |
          git add docs/*
          git commit -m "Deploy to GitHub Pages"
          git push origin main  # Push changes to the main branch
