name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to the branch you want to deploy from (e.g., 'main' or 'master')

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify the version of Node.js you're using

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Remove docs folder
        run: rm -rf docs
      
      - name: Create docs directory if not exists
        run: mkdir -p docs

      - name: Copy build to docs
        run: cp -r dist/public/* docs/

      - name: Commit and push to GitHub Pages
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push origin main  # Push to the 'main' branch or any other branch you want to deploy from
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # This automatically gets a token to push changes

