name: Build and Deploy to Docs

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'  # Change if you're using a different version

      - name: Install dependencies
        run: npm ci  # or 'npm install' if needed

      - name: Build the project
        run: npm run build  # this should generate 'dist/public'

      - name: Move build to docs folder
        run: |
          rm -rf docs
          mv dist/public docs

      - name: Commit and push docs folder
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Update docs with latest build"
          git push
        continue-on-error: true  # Prevents failure if there are no changes
